### ISSUE TITLE
BiDirectional

### ISSUE THREAD

**Issue by bkief** [pacman82/odbc2parquet#38]
Is there any aspirations to make this tool bidirectional, so you can import to SQL from Parquet?

**Comment by pacman82** [comment]
@bkief Yes there is. There is even a branch allowing to insert Strings and 64 Bit integers. <https://github.com/pacman82/odbc2parquet/compare/insert>.

Since getting all the corner cases right is some work, I thought I let it rest until someone shows interesst in the feature. I guess here we are ;-)

I would really like to know about the use case you have in mind. Would you assume the column names of the table match the ones in the parquet file? Would the parquet file have been created by this tool, or would it have a different source?

**Comment by pacman82** [comment]
Closing this issue since `0.5.10` is released with basic support for insert. If you want let me know if it is already useful to you.
