### ISSUE TITLE
Likely not writing parquet correctly

### ISSUE THREAD

**Issue by nevi-me** [pacman82/odbc2parquet#4]
While going through the code, I noticed that we write the values and definitions to the same length buffers, as per below:

```rust
self.def_levels[row_index] = def;
self.values_i32[row_index] = value;
```

I think this is incorrect, as we should only write values if the `definition > 0` (or 1 in our case with primitives).
This works out such that `vec![None, Some(35), None]` ends up with:

```rust
let defs = vec![0, 1, 0];
let vals = vec![35];
```
IIRC, the parquet crate will only complain if the values being written are less than valid definitions, so the above might not be surfacing itself in an error.

I tried to write a fairly large table that I know to be very sparse, and I reached a panic:

```rust
thread 'main' panicked at 'assertion failed: self.data.is_some()', parquet-1.0.1\src\data_type.rs:143:9
```

I have a suspicion that the panic is related to the above potential issue, but I'll have a look at it over the weekend or next week.

**Comment by pacman82** [comment]
Hello, you are indeed correct. The issue is easy enough to reproduce.

I cheated a bit though and used my setup for `odbc-api` to reproduce it. So far I've been hesitant to merge it into one workspace since odbc2parquet only builds on nightly.

Sadly though, now I need another transformation on the buffers, if there are NULLs present :-(.

Many thanks for reporting this Bug, it's very good to have someone with expertise on the Rust `parquet` crate looking over this repository.
