### ISSUE TITLE
Support UTF-16LE encoding

### ISSUE THREAD

**Issue by clemensvonschwerin** [pacman82/odbc2parquet#40]
Hey @pacman82,

I really like your tool, it's easy to use and fast for exporting data out of MSSQL. For me there is one issue though: I am using MSSQL Server 2016 which uses UTF-16LE encoding by default. This results in special characters being replaced by the Unicode Replacement Character in the target parquet file, which makes recovery impossible. Could you maybe add an option for supporting UTF-16LE encoding? I think also just a flag to write strings directly as varbinary in the parquet file could do the trick for me. 

Thank you, cheers, 
Clemens

**Comment by pacman82** [comment]
Hello Clemens, thanks for your kind words. I write this in my spare time mostly as a learning experience, but it means a lot to me that it actually helps people do stuff.

> I am using MSSQL Server 2016 which uses UTF-16LE encoding by default

Let's unpack that a bit. So I am sure that I got your problem right. Encodings in ODBC are a bit messy, mostly because there are so many of them. The one that matters here though is the encoding for the client side encoding for `SQLCHAR` character data. This is independent of the encoding of the data on the database and depends on your system locale. On Linux and OS-X this is UTF-8 by default, on Windows as of now it is not. My Windows System has Latin1 for example. If you ran the tool with verbose logging you should have seen this warning:

```
Non UTF-8 characters found in string. Try to execute odbc2parquet in a shell with UTF-8 locale. Value: {}
```

So you could configure your windows system locale no use utf-8, but that requires administrative priviliges and is still in Beta.

I could provide a flag which makes the encoding issues away independent of the system configuration, but it will cost in terms of IO, Memory and CPU. Still, if only I could find a way to change the system locale only for my process. (My first naive attempt of calling setlocal sadly failed).

I'll come back here once I researched a bit more. In the meanwhile I hope you can work around the issue (if not tell me, I'll hook you up with a quick fix).

**Comment by pacman82** [comment]
I'll be introducing a flag, and make it very likely the default on windows systems. I need to implemend a wide character buffer in the upstream `odbc-api` first though.

**Comment by clemensvonschwerin** [comment]
Hi Markus,

thank you for your helpful answer. Coming from the unix world and using windows for our current project all the encoding differences can get a bit confusing. As you said the issue was the encoding specified for the whole windows system which was then adopted by the odbc driver, specifically the region settings. After activating the "Beta: Use Unicode UTF-8 for worldwide language support" option on our test windows machine the encoding works like a charm.
Of course being able to do that in Powershell without administrative privileges or even better via the flag in odbc2parquet would be much appreciated. Thank you very much for your efforts!

Cheers,

Clemens

**Comment by pacman82** [comment]
Ironically, since you now have changed your system locale, you may want to set the flag to explicitly after I release the now version to get the current behaviour of the tool. As requesting utf-8 directly should be more performant.

**Comment by pacman82** [comment]
Version 0.5.8 with support for the new `--encoding` option is released. Mind the new default for windows platforms.
