### ISSUE TITLE
Build release assets for Ubuntu ARM64 as well

### ISSUE THREAD

**Issue by sindilevich** [pacman82/odbc2parquet#491]
Hello,

Currently, release assets are only created for Ubuntu AMD64. It is impossible to use the binary from within an Ubuntu AMR64 image, such as Mx Mac's.

It would be great to have binary releases for Ubuntu AMR64 as well.

Something similar to the options available for Powershell releases: https://github.com/PowerShell/PowerShell/releases.

Thank you in advance!

**Comment by pacman82** [comment]
Why not just build it directly for your ARM Mac?

GitHub currently offers to my knowledge no free ARM runners. Otherwise I would add binaries for ARM Mac. However it is not that cumbersome to build for either Ubuntu or Mac. You need a rust toolchain installed. You can use <https://rustup.rs> to install it. Second you need to install unixODBC. Third you can type `cargo install odbc2parquet` and you should have the executable available.

Happy to help you debug, if you share verbose enough error messages.

Best, Markus

**Comment by sindilevich** [comment]
Thank you for your quick and elaborate reply!

I was able to successfully build `odbc2parquet` on both Mac and an x86-64 Linux using the Rust docker image: `1.74.0-slim-bookworm`.

However, when I tried compiling `odbc2parquet` on an x86-64 Linux using the `1.74.0-alpine` docker image, the compilation failed. Before running `cargo install odbc2parquet` I added the `unixodbc-dev` package to the image. Yet still the compilation failed, unable to find the `lodbc` file. The short version of the error was: `ld: cannot find -lodbc`.

Is there a way to build `odbc2parquet` on Alpine Linux (on an ARM64/AMD64 machine)?

Thank you in advance!

**Comment by pacman82** [comment]
Alpine is difficult because it uses a Musl C-Library target. I do not think dynamic linking works with these in Rust out of the box. Choose a container which is based on a glibc and you will be fine.

**Comment by sindilevich** [comment]
Using a Debian docker image is easy, as Rust publishes a prebuilt image for that: `1.74.0-slim-bookworm`.

The only reason I wanted to use an Alpine docker image as the base was the fact the resulting image is about 4 times smaller than the _slim_ Debian one.

So, if the Alpine effort is _difficult_, but still _doable_, I'd appreciate any help in overcoming the Musl-related issues.

Thank you in advance!

**Comment by pacman82** [comment]
I do not know whether it is doable or not. If size is an issue I just want to highlight the possibility to just build directly for ARM Mac OS. This is fairly easy and has been done before.

If you need containers I would go down the route of looking for a small libc based image.

**Comment by sindilevich** [comment]
Yes, I need a containerized build process. It would be wonderful if you could point me to a small `libc`-based image, where `odbc2parquet` could be built from source.

I really appreciate any help you can provide.

**Comment by pacman82** [comment]
everything there you get the rust `aarch64-unknown-linux-gnu` target toolchain to run will work. Which docker base images is smallest is for you to figure out.

**Comment by sindilevich** [comment]
Excellent, @pacman82! Thank you for your help!

**Comment by pacman82** [comment]
@sindilevich It may be of interest to you that `odbc2parquet 5.0.0` is also released for MacOS M1

**Comment by sindilevich** [comment]
> @sindilevich It may be of interest to you that `odbc2parquet 5.0.0` is also released for MacOS M1

Thank you, @pacman82, it is indeed of interest to me!

**Comment by sindilevich** [comment]
Hello,

I've been using `odbc2parquet` for almost a year now, and I currently need to run it within an Ubuntu ARM64 Docker image. However, I see that you only provide an `odbc2parquet-x86_64-ubuntu.gz` artifact, which is designed for Ubuntu AMD64.

Would it be possible to add an Ubuntu ARM64-compatible version of the odbc2parquet artifact as well, similar to the `odbc2parquet-macos-m1` artifact?

**Comment by pacman82** [comment]
Hello @sindilevich ,

Possible yes. Straight forward, no. Straight forward would mean for me, that I can just add another Ubuntu ARM runner to execute the release pipeline on. To my knowledge all ARM runners right now, both on GitHub and Fly-Ci are also Mac runners, rather than Ubuntu.

I could see it possible to cross build an Ubuntu Artefact on an M1 or M2 Mac though. I am open to contributions. However, since I do not only need to merge the PR, but also to support it, I would probably reject it if the pipeline gets too Arcane 😅 .

If cross building turns out to be straight forward, and easy enough for my head to understand, I'd be happy to merge it though.

Alternatively, maybe this recently contributed GEM of a Dockerfile in the Readme might be helpluf to you:

```Dockerfile
FROM rust:alpine AS builder

RUN apk add --no-cache musl-dev unixodbc-static
# In addition to unixodbc you also want to install the database drivers you need and `COPY` them over to the `runner`

WORKDIR /src/odbc2parquet
COPY . .
RUN cargo build --release

FROM scratch AS runner

COPY --from=builder /src/odbc2parquet/target/release/odbc2parquet /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/odbc2parquet"]
```

Best, Markus

**Comment by sindilevich** [comment]
Hello @pacman82,

Added a PR for the possible solution for an Ubuntu ARM64 cross build: https://github.com/pacman82/odbc2parquet/pull/629.

**Comment by sindilevich** [comment]
@pacman82, thank you for accepting my contribution to the project!

Now, that https://github.com/pacman82/odbc2parquet/pull/629 has been merged, will eagerly wait for the new artifacts to be published for testing!

**Comment by pacman82** [comment]
@sindilevich thanks for contributing.

**Comment by pacman82** [comment]
it seems though, the actions fail

**Comment by pacman82** [comment]
I'll fix the release.

I reverted the ubuntu arm job for now. Probably not to complicated to make it work. My time for private projects is very tight right now.

My ask would be, to just build the Ubuntu arm artifact as part of push rather than release, so we can test it out on a branch before merging. I'll move the code over to release.yml and publish the gz to GitHub myself after merge.

Best, Markus

**Comment by sindilevich** [comment]
Hello @pacman82,
Added a PR to build the Windows x86 and Ubuntu ARM64 artifacts correctly: https://github.com/pacman82/odbc2parquet/pull/633.
I used a modified version of `release.yml` to run the build workflows on push.

**Comment by sindilevich** [comment]
Hello @pacman82,
I saw there are numerous warnings running GitHub Actions.
Fixed the warnings.

**Comment by pacman82** [comment]
`odbc2parquet 6.0.7` is released. It also comes with a binary release for Ubuntu ARM thanks to you. Closing this issue.
