### ISSUE TITLE
Exporter adding trailing zero's in when exporting from PostgreSQL Numeric dtype

### ISSUE THREAD

**Issue by adriansabas** [pacman82/odbc2parquet#532]
Hi, 

I noticed that odbc2parquet converts PostgreSQL numeric data type to decimal(28,6) in parquet file, which is adding trailing zero's to data.

Let me explain with an example, below is a screenshot how it looks in postgre. Till 50th record there are numeric values as seen in postgre, and those values have been exported to parquet and then imported again. So 51st record is first imported from parquet, as You can see conversion added trailing zero's.
![image](https://github.com/pacman82/odbc2parquet/assets/120106508/d533d084-60e5-4353-99e4-61069eb366a8)

I checked in python data types of parquet file.
```
import pandas as pd
parquet_file_path = 'odbc2parquet.parquet'
df = pd.read_parquet(parquet_file_path, engine='pyarrow', dtype_backend = 'pyarrow')
df[['price_amount','base_unit_amount','quantity']].dtypes
```

That gave me:
```
price_amount        decimal128(28, 6)[pyarrow]
base_unit_amount    decimal128(28, 6)[pyarrow]
quantity                        int32[pyarrow]
dtype: object
```

My guess is that because postgre's numeric doesn't have explicitly given scale and precision, Your code just casts it to some maximal decimal scale and precision.

Maybe there is a possibility to get rid of trailing zeros and shrink decimal to maximal precision found in data itself?

**Comment by pacman82** [comment]
Hello @adriansabas ,

sorry for the long response time.

> My guess is that because Postgre's numeric doesn't have explicitly given scale and precision

This is the guess which is correct. However it is only half correct. You could change your date schema to give it explicit scale and precision. If you own the database schema I would suggest to sanatize it. Base unit amount to me sounds like an integer, and you want the price restricted to likely something with scale two. Tipp: Often it is better to model even prices as integers rather than decimals and express them in cents.

I also think we see an artifact here, of the verbose string representation being used to insert into the database. However it is ultimately up to Postgres to decide how it wants to store the values and to decide `50.0` is something different from `50.000`.

If you do not have the option to sanatize the schema, and since your issue suggests some familiarity with Python, you could also try to use the `arrow-odbc` Python bindings <https://github.com/pacman82/arrow-odbc-py> to post process the data, or adapt the schema beforehand. `arrow-odbc` allows you to pass an explicit schema.

Yet another approach would be to explicitly cast the numeric type in the queries to a numeric type with defined scale in the SQL statement passed to `odbc2parquet`.

Hope this helps. Best,

Markus

**Comment by adriansabas** [comment]
Thanks for answer and also sorry for long response time,

> However it is ultimately up to Postgres to decide how it wants to store the values and to decide 50.0 is something different from 50.000.

I'm not really sure about that one, the numbers without trailing zero's comes from my own simple parquet exporter/importer written in Python. In there i have a workoaround that throws numeric to string before creating parquet, to avoid trailing zero's.

So If postgres have Numeric type column without given scale and precision each row might have its own like in example that I gave.

To wrap it up if we have value '50.0' Numeric

When You load it in parquet as a string and then insert to postgres, database will store it and show as a '50.0'

Your code I assume, when it creates column from Numeric it creates decimal128(28, 6) beacause it didn't had exact scale and precision given then it create column with maximum values for those.

So it converts value '50.0' to '50.000000' because precision is 6 and then after insert to postgre You have additional trailin zero's.

Of course I know that adding scale and precision to my columns would be a solution but my suggestion was to maybe think about some solution in odbc2parquet other than "just assume maximum" for that case when column type is given without explicitly stated size scale etc.


On the other hand issue might be closed because it's more a suggestion and there is workaround on a schema/sql level to avoid trailing zero's.

**Comment by pacman82** [comment]
> Your code I assume, when it creates column from Numeric it creates decimal128(28, 6) beacause it didn't had exact scale and precision given then it create column with maximum values for those.

Kind of, but not quit. If you run it with more verbose output by adding `-vvv` to the command line, you will see that 28 precision and 6 scale are values reported by the PostgreSQL ODBC driver. So there is no special case in `odbc2parquet` how to treat a `NUMERIC` column without precision. It just acts on what the driver tells it.

ODBC does not have a concept of a Decimal column without Precision and Scale. Nor does it have a concept of a column in which each row would have its own precision and scale. All these translations are up to the PostgreSQL driver.

**Comment by adriansabas** [comment]
Alright everything clear then, so i guess explicit scale and precision might be the only appropriate way.

Thank You very much for answer, I'm closing the issue.

**Comment by pacman82** [comment]
> Thank You very much for answer, I'm closing the issue.

You are welcome
