### ISSUE TITLE
Spark import error - not supporting FIXED_LEN_BYTE_ARRAY

### ISSUE THREAD

**Issue by swalker-setfords** [pacman82/odbc2parquet#63]
Great tool btw. Exactly what I was after.

Though I am struggling to use the results in spark.

Caused by: org.apache.spark.sql.AnalysisException: Illegal Parquet type: FIXED_LEN_BYTE_ARRAY

Is there a way to adjust the type mapping in any way? Or anything you can think of to help out here

**Comment by pacman82** [comment]
Currently there is no command line Option to adjust the type mapping. The tool chooses itself the type it thinks it fits best. Yet I am always open to suggesttions for enhancements (and PRs ;-)). There might also be a pragmatic workaround. The tool chooses `FIXED_LEN_BYTE_ARRAY` if the type in the result set that is returned by the database is fixed sized, but you might be able to cast it directly in the SQL query itself.

Lets say `a` is of type CHAR(3).

E.g. instead of

```
SELECT a FROM MyTable
```

query

```
SELECT Cast(a as VARCHAR(3)) FROM MyTable
```

`VARCHAR` or `VARBINARY` would be mapped to `BYTE_ARRAY` and not `FIXED_LEN_BYTE_ARRAY`.

Please tell me if this can solve your problem.

Cheers, Markus

**Comment by swalker-setfords** [comment]
Thanks Markus.

My specific issue is in relation to whole table export, so tricky to cast.

Like I say, not an issue with your bit of kit. Just wasn’t sure if there were switches I could use to re-wire the mapping to varbinary or another type.

**Comment by pacman82** [comment]
There seems to be a stale PR in Spark addressing this issue: https://github.com/apache/spark/pull/20826

I am open to introducing flags changing the mapping. These could be fairly specific like `--prefer-varbinary` or `--prefer-varchar`. It might also be geared more towards the use case like `--spark-compatible`. The latter would probably be harder to test, since we would have to introduce Spark to the test suite. Yet if you help me set it up, I'd be game.

**Comment by pacman82** [comment]
Version `0.6.4` introduces the `--prefer-varbinary` flag. Please let me know if the output works for you now.

**Comment by pacman82** [comment]
ping @swalker-setfords
